### ISSUE TITLE
Cannot uninstall clippy

### ISSUE THREAD

**Issue by SoonDead** [citizenmatt/resharper-clippy#3]
* Installed clippy on R# 10.0.1
 * Updated R# to 10.0.2
 * Tried to uninstall clippy but it threw an error that it cannot write a file.
 * Restarted VS in admin mode, but clippy was not present any more in the extension manager, although clippy is still there.
 * Restarted VS, nothing changed.
 * I'm stuck with clippy. I can see/use it but can't uninstall.

R# is installed in "All Users" mode and therefore it is in the Program Files.

**Comment by citizenmatt** [comment]
Hmm. That's an odd one. [Extensions aren't supported in "All Users" mode](https://youtrack.jetbrains.com/issue/RSRP-448743), so I'm not sure how it got installed in the first place. I'd suggest, if you can, uninstalling ReSharper completely, and reinstalling it as a normal, per-user extension. That will probably get rid of the Clippy extension. If not, let me know, and we'll see what we can do to remove it from per-user.

**Comment by SoonDead** [comment]
I have uninstalled R#, deleted every reference/setting to it I could find, reinstalled it in single user mode and Clippy was gone for good.

Did not know about "all users" not supporting extensions, thanks for linking the issue.
